// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsq9kilEzfkG1ZR11ObiNt03mTS033Bz8',
    appId: '1:1072933801746:web:3bc7b1ea5f7cb833912dcb',
    messagingSenderId: '1072933801746',
    projectId: 'sendsmswithlink',
    authDomain: 'sendsmswithlink.firebaseapp.com',
    storageBucket: 'sendsmswithlink.appspot.com',
    measurementId: 'G-X04MF2GNP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9U1xRaEsW-xpYcyuDitnYuT8RRosW90',
    appId: '1:1072933801746:android:b923d32933b651f8912dcb',
    messagingSenderId: '1072933801746',
    projectId: 'sendsmswithlink',
    storageBucket: 'sendsmswithlink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5tU0oTpz50e-4805PpOeUBRduFBEO7A',
    appId: '1:1072933801746:ios:03fc43d52ef2d8c4912dcb',
    messagingSenderId: '1072933801746',
    projectId: 'sendsmswithlink',
    storageBucket: 'sendsmswithlink.appspot.com',
    iosClientId: '1072933801746-hudhc3jndig02tpm7tu189u33lqo2dl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditCardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5tU0oTpz50e-4805PpOeUBRduFBEO7A',
    appId: '1:1072933801746:ios:d74b75aae733a936912dcb',
    messagingSenderId: '1072933801746',
    projectId: 'sendsmswithlink',
    storageBucket: 'sendsmswithlink.appspot.com',
    iosClientId: '1072933801746-g5hffr63g8qa0jp6396b5mhn1ibp9lef.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditCardApp.RunnerTests',
  );
}
